import type { Metadata } from "next";
import "./globals.css";
import { generateCssVariables } from "@/design-system/utils/generateCssVariables";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Geração das variáveis CSS no lado do servidor
  const cssVariables = generateCssVariables();

  return (
    <html lang="en">
      <head>
        {/*
          Aqui estamos injetando as variáveis CSS geradas dinamicamente
          no <head> do documento como uma tag <style>.
          Isso garante que elas estejam disponíveis globalmente para todos os CSS.
        */}
        <style dangerouslySetInnerHTML={{ __html: cssVariables }} />
      </head>
      <body>
        {children}
      </body>
    </html>
  );
}